name: Generate static map

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: URL to capture
        required: false
        default: "http://89.167.106.119:3001/map"
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  screenshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure images directory exists
        run: mkdir -p images

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: ${{ inputs.website_url || 'http://89.167.106.119:3001/map' }}
          mode: page
          output: images/static-map.png

      - name: Commit updated map
        run: |
          git config user.name "DominikBrezovsek"
          git config user.email "dominik.brezovsek@student.um.si"

          git add images/static-map.png

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update static map"
          git push
